---
language: go

# avoiding link error
# https://github.com/travis-ci/gimme/issues/174
dist: xenial

go:
  - 1.13.x
  - 1.12.x
  - 1.11.x

env:
  global:
    # enable go modules
    - GO111MODULE=on
  jobs:
    # for sqlite3
    - TAGS= GOEN_TEST_CONNSTR=
    # for postgres
    - TAGS="-tags postgres" GOEN_TEST_CONNSTR="dbname=testing user=postgres sslmode=disable"

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  # create database
  - psql -c 'create database testing;' -U postgres

script:
  # when go1.11.x golangci-lint always fail by https://github.com/golang/go/issues/30355
  # install deps first to avoid it
  - go mod download
  - make lint
  - go test ${TAGS} -v ./...
